# Generated by Django 4.2.4 on 2023-08-16 03:57

from django.db import migrations
import ulog.manger


class Migration(migrations.Migration):

    dependencies = [
        ('ulog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cuser',
            managers=[
                ('objects', ulog.manger.CUserManger()),
            ],
        ),
    ]
