# Generated by Django 4.2.4 on 2023-08-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulog', '0002_alter_cuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='photos/categories')),
            ],
        ),
    ]
